### ISSUE TITLE
Documentation of function types.

### ISSUE THREAD

**Issue by davidbjames** [EmilioPelaez/CGMathSwift#1]
Hey! This is a great little library. I'm currently working on a library that helps make UIView manipulation for the purpose of doing complex animations, easier, and CGMathSwift looks like a very useful library to lean on.

The README mentions "lerp, inverse lerp, clamp and remap" functions, which look very interesting. I understand conceptually what a "lerp" is but not the other 3, so some kind of description would be nice. Also it would be nice to see concrete examples of each function to help understand them.

What do you think?

**Comment by EmilioPelaez** [comment]
Agreed, I'll add a more comprehensive documentation soon. Thanks for the input!

**Comment by EmilioPelaez** [comment]
@davidbjames I rewrote `CGMath` in Swift and added a more comprehensive documentation. Check it out [here](https://github.com/EmilioPelaez/CGMath). `CGMathSwift` has been deprecated.
